import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {Header,Footer} from "./_Compenents/mianLayout"
import { DarkMode } from "./_Compenents/darkMode";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
    <html lang="en" data-theme='dark' className="dark"> 
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen dark:bg-gray-900`}
      >
        <DarkMode/>
          <Header/>
          <main className='flex-grow'>
             {children}
          </main>
          <Footer/>
      </body>
    </html>
  );
}
